import { z } from "zod";

import { createTRPCRouter, publicProcedure } from "~/server/api/trpc";

export const titleRouter = createTRPCRouter({
  getAiTitle: publicProcedure.query(() => {
    return "Title generated by AI";
  }),
});
